version: "3.9"

services:
  web:
    build: .
    ports:
      - "8080:8082"
    # env variabls can be read from a file
    env_file:
      - app.env
    # environment:
    #   - APP_PORT
    #   - RUNTIME_SETUP
    #   - DB_DRIVER
    #   - SERVER_ADDRESS
    volumes:
      - ./logs:/app/logs
    links:
      - redis
  redis:
    image: redis:alpine