name: Docker Image CI

on:
  push:
    branches-ignore:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag booklibrary:$(date +%s)